version: "3.2"

services:
  postgres:
    image: postgres:10.0
    ports:
      - "15432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: aleph
      POSTGRES_PASSWORD: aleph
      POSTGRES_DATABASE: aleph

  elasticsearch:
    image: alephdata/aleph-elasticsearch:6
    restart: on-failure
    environment:
      - http.cors.allow-origin="http://dejavu:1358"
      - http.cors.enabled=true
      - http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
      - http.cors.allow-credentials=true
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data

  dejavu:
    image: appbaseio/dejavu
    ports:
      - "1358:1358"
    links:
      - elasticsearch

  rabbitmq:
    image: rabbitmq
    hostname: queue
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

  redis:
      image: redis:alpine
      command: ["redis-server", "--appendonly", "yes"]
      volumes:
        - redis-data:/data

  convert-document:
    image: alephdata/aleph-convert-document
    restart: on-failure
    tmpfs:
      - /tmp
      - /root/.config
    expose:
      - 3000

  recognize-text:
    image: alephdata/aleph-recognize-text
    restart: on-failure
    expose:
      - 50000
  
  extract-entities:
    image: alephdata/aleph-extract-entities
    restart: on-failure
    expose:
      - 50000

  app:
    image: alephdata/aleph
    command: /bin/bash
    links:
      - postgres
      - elasticsearch
      - rabbitmq
      - redis
      - convert-document
      - recognize-text
      - extract-entities
    tmpfs: /tmp
    volumes:
      - archive-data:/data
      - "/data/workspaces/drapp/code/aleph/aleph:/aleph/aleph"
      - "/data/workspaces/drapp/code/aleph/contrib:/aleph/contrib"
      - "/data/workspaces/drapp/code/aleph/mappings:/aleph/mappings"
      - "/:/host"
    cap_add:
      - SYS_PTRACE
    environment:
      ALEPH_DEBUG: 'true'
      ALEPH_SECRET_KEY: 'development'
      ALEPH_OAUTH: 'false'
      ALEPH_ARCHIVE_TYPE: 'file'
    env_file:
      - aleph.env

  api:
    image: alephdata/aleph
    command: python3 aleph/manage.py runserver -h 0.0.0.0 -p 5000
    expose:
      - 5000
    ports:
      - "5000:5000"
    restart: on-failure
    links:
      - postgres
      - elasticsearch
      - rabbitmq
      - redis
      - convert-document
      - recognize-text
      - extract-entities
    tmpfs: /tmp
    volumes:
      - archive-data:/data
      - "/data/workspaces/drapp/code/aleph/aleph:/aleph/aleph"
      - "/:/host"
    environment:
      ALEPH_DEBUG: 'true'
      ALEPH_SECRET_KEY: 'development'
      ALEPH_ARCHIVE_TYPE: 'file'
    env_file:
      - aleph.env
  
  ui:
    image: alephdata/aleph-ui
    links:
      - api
    command: npm run start
    ports:
      - "8080:3000"
    volumes:
      - "/data/workspaces/drapp/code/aleph/ui/src:/alephui/src"
      - "/data/workspaces/drapp/code/aleph/ui/public:/alephui/public"
      - "/data/workspaces/drapp/code/aleph/ui/.tx:/alephui/.tx"
      - "/data/workspaces/drapp/code/aleph/ui/package.json:/alephui/package.json"
    environment:
      REACT_APP_API_ENDPOINT: '/api/2'
    env_file:
      - aleph.env

volumes:
  archive-data: {}
  elasticsearch-data: {}
  postgres-data: {}
  rabbitmq-data: {}
  redis-data: {}