apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  namespace: aleph
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: data@occrp.org
    privateKeySecretRef:
      name: letsencrypt-staging
    http01: {}
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: aleph
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: data@occrp.org
    privateKeySecretRef:
      name: letsencrypt-prod
    http01: {}
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: tls-staging.data.occrp.org
  namespace: aleph
spec:
  secretName: tls-staging.data.occrp.org
  dnsNames:
    - staging.data.occrp.org
  acme:
    config:
      - http01:
          ingress: ingress-nginx
        domains:
          - staging.data.occrp.org
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer