kind: ConfigMap
apiVersion: v1
metadata:
  name: search-config
  namespace: aleph
data:
  GOOGLE_APPLICATION_CREDENTIALS: /secrets/service-account.json
  C_FORCE_ROOT: 'true'
  ALEPH_ELASTICSEARCH_URI: http://search-index.aleph.svc.cluster.local:9200/
  ALEPH_ELASTICSEARCH_SHARDS: {{ .Values.config.ALEPH_ELASTICSEARCH_SHARDS | quote }}
  ALEPH_ENTITIES_INDEX: aleph-entity-v1
  ALEPH_ENTITIES_INDEX_SET: aleph-entity-v1
  ALEPH_RECORDS_INDEX: aleph-record-v1
  ALEPH_RECORDS_INDEX_SET: aleph-record-v1
  ALEPH_COLLECTIONS_INDEX: aleph-collection-v1
  ALEPH_BROKER_URI: amqp://guest:guest@search-queue.aleph.svc.cluster.local:5672
  ALEPH_REDIS_URL: redis://search-redis.aleph.svc.cluster.local:6379/0
  ALEPH_ENTITIES_SERVICE: search-extract-entities.aleph.svc.cluster.local:50000
  ALEPH_OCR_SERVICE: search-recognize-text.aleph.svc.cluster.local:50000
  UNOSERVICE_URL: http://search-convert-document.aleph.svc.cluster.local:3000/convert
  ALEPH_DEBUG: 'false'
  ALEPH_CACHE: 'true'
  ALEPH_EAGER: 'false'
  ALEPH_URL_SCHEME: {{ .Values.config.ALEPH_URL_SCHEME }}
  ALEPH_APP_TITLE: {{ .Values.config.ALEPH_APP_TITLE }}
  ALEPH_APP_NAME: aleph
  ALEPH_UI_URL: {{ .Values.config.ALEPH_UI_URL }}
  ALEPH_FAVICON: https://cdn.occrp.org/common/logo/RedTransparent_globe.png
  ALEPH_LOGO: https://cdn.occrp.org/common/logo/RedTransparent_globe.png
  ALEPH_CORS_ORIGINS: '*'
  ALEPH_ARCHIVE_TYPE: {{ .Values.config.ALEPH_ARCHIVE_TYPE }}
  ALEPH_ARCHIVE_BUCKET: {{ .Values.config.ALEPH_ARCHIVE_BUCKET }}
  ALEPH_PASSWORD_LOGIN: {{ .Values.config.ALEPH_PASSWORD_LOGIN | quote }}
  ALEPH_ADMINS: {{ .Values.config.ALEPH_ADMINS }}
  ALEPH_MAIL_FROM: {{ .Values.config.ALEPH_MAIL_FROM }}
  ALEPH_MAIL_HOST: {{ .Values.config.ALEPH_MAIL_HOST }}
  ALEPH_MAIL_USERNAME: {{ .Values.config.ALEPH_MAIL_USERNAME }}
  ALEPH_MAIL_PORT: "587"
  ALEPH_MAIL_TLS: 'true'
  ALEPH_OAUTH: {{ .Values.config.ALEPH_OAUTH | quote }}
  ALEPH_OAUTH_KEY: {{ .Values.config.ALEPH_OAUTH_KEY }}
  ALEPH_OAUTH_NAME: {{ .Values.config.ALEPH_OAUTH_NAME }}
  ALEPH_OAUTH_BASE_URL: {{ .Values.config.ALEPH_OAUTH_BASE_URL }}
  ALEPH_OAUTH_AUTHORIZE_URL: {{ .Values.config.ALEPH_OAUTH_AUTHORIZE_URL }}
  ALEPH_OAUTH_TOKEN_URL: {{ .Values.config.ALEPH_OAUTH_TOKEN_URL }}
  ALEPH_OAUTH_SCOPE: {{ .Values.config.ALEPH_OAUTH_SCOPE }}
  ALEPH_OAUTH_TOKEN_METHOD: {{ .Values.config.ALEPH_OAUTH_TOKEN_METHOD }}
  ALEPH_OCR_VISION_API: {{ .Values.config.ALEPH_OCR_VISION_API | quote }}
