apiVersion: v1
kind: Service
metadata:
  name: search-convert-document
  namespace: aleph
  labels:
    app: search-convert-document
spec:
  selector:
    app: search-convert-document
  type: ClusterIP
  ports:
    - port: 3000
      protocol: "TCP"
      name: api
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: search-convert-document
  namespace: aleph
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: search-convert-document
  minReplicas: {{ .Values.convertdocument.minReplicas }}
  maxReplicas: {{ .Values.convertdocument.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 80
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: search-convert-document-policy
  namespace: aleph
spec:
  podSelector:
    matchLabels:
      app: search-convert-document
  policyTypes:
    - Egress
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-convert-document
  namespace: aleph
  labels:
    app: search-convert-document
spec:
  selector:
    matchLabels:
      app: search-convert-document
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: search-convert-document
    spec:
      affinity: # Ask k8s to preferr that pods are placed across zones if available
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - {{ .Values.global.reponame }}
              topologyKey: failure-domain.beta.kubernetes.io/zone
      restartPolicy: Always
      containers:
        - name: search-convert-document
          image: alephdata/aleph-convert-document:{{ .Values.global.imagetag }}
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              name: http
          resources:
            requests:
              cpu: {{ .Values.convertdocument.resources.requests.cpu }}
              memory: {{ .Values.convertdocument.resources.requests.memory }}
            limits:
              cpu: {{ .Values.convertdocument.resources.limits.memory }}
              memory: {{ .Values.convertdocument.resources.limits.memory }}
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 15
            timeoutSeconds: 301
            periodSeconds: 302
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 15
            timeoutSeconds: 301
            periodSeconds: 302
