apiVersion: v1
kind: Service
metadata:
  name: search-extract-entities
  namespace: aleph
  labels:
    app: search-extract-entities
spec:
  selector:
    app: search-extract-entities
  ports:
    - port: 50000
      targetPort: 50000
      protocol: "TCP"
      name: grpc-api
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: search-extract-entities
  namespace: aleph
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: search-extract-entities
  minReplicas: {{ .Values.extractentities.minReplicas }}
  maxReplicas: {{ .Values.extractentities.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 90
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-extract-entities
  namespace: aleph
  labels:
    app: search-extract-entities
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search-extract-entities
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: search-extract-entities
    spec:
      restartPolicy: Always
      containers:
        - name: search-extract-entities
          image: alephdata/aleph-extract-entities:{{ .Values.global.imagetag }}
          imagePullPolicy: Always
          ports:
            - containerPort: 50000
              name: grpc-api
          resources:
            requests:
              cpu: {{ .Values.extractentities.resources.requests.cpu }}
              memory: {{ .Values.extractentities.resources.requests.memory }}
            limits:
              cpu: {{ .Values.extractentities.resources.limits.memory }}
              memory: {{ .Values.extractentities.resources.limits.memory }}
