apiVersion: v1
kind: Service
metadata:
  name: search-redis
  namespace: aleph
spec:
  ports:
    - port: 6379
      name: search-redis
  selector:
    app: search-redis
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: search-redis
  namespace: aleph
spec:
  selector:
    matchLabels:
      app: search-redis
  serviceName: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: search-redis
    spec:
      containers:
        - name: redis
          image: redis:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 6379
              name: search-redis
          args:
            - --save
            - "1200"
            - "1"
            - --maxmemory
            - {{ .Values.redis.maxMemory }}
            - --maxmemory-policy
            - volatile-ttl
          resources:
            requests:
              memory: {{ .Values.redis.resources.requests.memory }}
              cpu: {{ .Values.redis.resources.requests.cpu }}
            limits:
              memory: {{ .Values.redis.resources.limits.memory }}
              cpu: {{ .Values.redis.resources.limits.cpu }}
          volumeMounts:
            - name: data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: ssd
        resources:
          requests:
            storage: 10Gi